<?php /** @var Nascenia\Zend\View\Renderer\PhpRenderer $this */ ?>
<?php /** @var NasRec\Entity\Application[] $applications */ ?>

<table class="table">
    <thead>
        <tr>
            <th>#</th>
            <th>Status</th>
            <th>Name</th>
            <th>Position</th>
            <th>Date</th>
            <th>Resume</th>
        </tr>
    </thead>

    <tbody>
        <?php if (count($applications) == 0): ?>
            <tr>
                <td colspan="5">
                    <em>There are currently no applications for review.</em>
                </td>
            </tr>
        <?php endif ?>

        <?php foreach ($applications as $application): ?>
            <tr>
                <td><?= $application->getId() ?></td>
                <td><?= $application->getStatus() ?></td>
                <td>
                    <a href="<?= $this->url('nas-rec-admin/application/view', array('application-id' => $application->getId())) ?>">
                        <?= $this->escapeHtml($application->getUser()->getDisplayName()) ?>
                    </a>
                    <br/>
                    <?= $this->escapeHtml($application->getUser()->getEmail()) ?>
                </td>
                <td><?= $application->getPosition()->getName() ?></td>
                <td><?= $application->getCreatedAt()->format('d M Y') ?></td>
                <td>
                    <a href="<?= $this->uploads()->get($application->getResume()) ?>">View Resume</a>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
