<?php /** @var Nascenia\Zend\View\Renderer\PhpRenderer $this */ ?>

<?php $this->headLink()
    ->appendStylesheet('//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css')
    ->appendStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css') ?>

<!DOCTYPE html>
<html>

<head>
    <?= $this->headTitle() ?>
    <?= $this->headLink() ?>
    <?= $this->headStyle() ?>
    <?= $this->headScript() ?>
</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand" href="<?= $this->url('nas-rec-public') ?>">Nascenia Recruitment System</a>
            </div>

            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <?php if ($this->identity()): ?>
                        <li><span class="navbar-text"><?= $this->identity()->getEmail() ?></span></li>
                        <li><a href="<?= $this->url('nas-rec-public/auth/logout') ?>">Logout</a></li>
                    <?php endif ?>
                </ul>
            </div>
        </div>
    </nav>

    <div>
        <div class="container">
            <?= $this->render('nascenia/wrapper/flash') ?>

            <?= $content ?>
        </div>
    </div>

    <?= $this->inlineScript() ?>
</body>

</html>
