<?php /** @var Nascenia\Zend\View\Renderer\PhpRenderer $this */ ?>

<?php use Zend\Mvc\Controller\Plugin\FlashMessenger; ?>

<?php $this->headLink()->appendStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css') ?>

<!DOCTYPE html>
<html>

<head>
    <?= $this->headTitle() ?>
    <?= $this->headLink() ?>
    <?= $this->headStyle() ?>
    <?= $this->headScript() ?>
</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="<?= $this->url('nas-rec-public') ?>">Nascenia Recruitment System</a>
            </div>
        </div>
    </nav>

    <div>
        <div class="container">
            <?= $this->render('nascenia/wrapper/flash') ?>

            <?= $content ?>
        </div>
    </div>

    <?= $this->inlineScript() ?>
</body>

</html>
