routes:

  nas-rec-public:
      type: Literal
      options:
        route: /
        defaults:
          controller: NasRecPublic:Application
          action: create
      may_terminate: true
      child_routes:
