routes:

  nas-rec-admin:
      type: Literal
      options:
        route: /admin
        defaults:
          controller: NasRecAdmin:Index
          action: index
      may_terminate: true
      child_routes:

        application:
          type: Literal
          options:
            route: /application
            defaults:
              controller: NasRecAdmin:Application
          child_routes:

            view:
              type: Segment
              options:
                route: /:application-id/view
                defaults:
                  action: view


        position:
          type: Literal
          options:
            route: /position
            defaults:
              controller: NasRecAdmin:Position
